import fs from "node:fs";
import path from "node:path";

const PAGE_FILES = ["page.tsx", "page.ts", "page.jsx", "page.js"];

export interface GenerateRoutesOptions {
  /** Root of the Next.js `app` directory. Default: `<cwd>/app`. */
  appDir?: string;
  /** Output file path. Extension decides the format (`.ts`/`.js` or `.json`). */
  out?: string;
  /** Log the resulting routes to stdout. Default: `true`. */
  log?: boolean;
}

function hasPage(dir: string): boolean {
  return PAGE_FILES.some((f) => fs.existsSync(path.join(dir, f)));
}

function walk(dir: string, base = ""): string[] {
  return fs.readdirSync(dir).flatMap((name) => {
    // Ignore private folders, route handlers and parallel routes.
    if (name.startsWith("_") || name === "api" || name.startsWith("@")) {
      return [];
    }

    const full = path.join(dir, name);
    if (!fs.statSync(full).isDirectory()) return [];

    // Route groups: (group) contribute no path segment.
    const segment = name.startsWith("(") && name.endsWith(")") ? "" : name;
    const route = segment ? `${base}/${segment}` : base;

    const self = hasPage(full) ? [route || "/"] : [];
    return [...self, ...walk(full, route)];
  });
}

/**
 * Walk the Next.js `app` directory and return the sorted list of route
 * patterns (dynamic segments preserved, e.g. `/docs/[...slug]`).
 */
export function collectRoutes(appDir: string): string[] {
  if (!fs.existsSync(appDir)) {
    throw new Error(`next-smart-router: app directory not found at "${appDir}"`);
  }
  return Array.from(new Set(["/", ...walk(appDir)])).sort();
}

function serialize(routes: string[], out: string): string {
  if (out.endsWith(".json")) {
    return JSON.stringify(routes, null, 2) + "\n";
  }
  return (
    `/* AUTO-GENERATED by next-smart-router — DO NOT EDIT */\n` +
    `export const ROUTES = new Set(${JSON.stringify(routes, null, 2)});\n`
  );
}

/**
 * Generate a route manifest from a Next.js `app` directory.
 * Returns the collected routes.
 */
export function generateRoutes(options: GenerateRoutesOptions = {}): string[] {
  const appDir = options.appDir ?? path.join(process.cwd(), "app");
  const out = options.out ?? path.join(process.cwd(), "route-manifest.ts");

  const routes = collectRoutes(appDir);

  fs.mkdirSync(path.dirname(path.resolve(out)), { recursive: true });
  fs.writeFileSync(out, serialize(routes, out));

  if (options.log ?? true) {
    // eslint-disable-next-line no-console
    console.log(
      `✅ next-smart-router: wrote ${routes.length} routes to ${out}`
    );
  }

  return routes;
}
